AWSTemplateFormatVersion: '2010-09-09'
Description: Application Load Balancer

Parameters:
  ProjectName:
    Type: String
  VpcId:
    Type: String
  AlbSecGroupId:
    Type: String
  PubSubNat1Id:
    Type: String
  PubSubNat2Id:
    Type: String

Resources:
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${ProjectName}-alb'
      Scheme: internet-facing
      Type: application
      SecurityGroups:
        - !Ref AlbSecGroupId
      Subnets:
        - !Ref PubSubNat1Id
        - !Ref PubSubNat2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-alb'

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub '${ProjectName}-tg'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      Matcher:
        HttpCode: 200-399
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-tg'

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:
  TargetGroupArn:
    Value: !Ref TargetGroup
  AlbDns:
    Value: !GetAtt LoadBalancer.DNSName
  AlbZoneId:
    Value: !GetAtt LoadBalancer.CanonicalHostedZoneID