AWSTemplateFormatVersion: '2010-09-09'
Description: Auto scaling web tier

Parameters:
  ProjectName:
    Type: String
  WebSecGroupId:
    Type: String
  PrivSubWeb1Id:
    Type: String
  PrivSubWeb2Id:
    Type: String
  TargetGroupArn:
    Type: String
  InstanceType:
    Type: String
  KeyName:
    Type: String
    Default: ""
  UserData:
    Type: String
    Default: ""
  MinSize:
    Type: Number
    Default: 1
  MaxSize:
    Type: Number
    Default: 4
  DesiredCapacity:
    Type: Number
    Default: 2
  CpuTarget:
    Type: Number
    Default: 65

Conditions:
  HasKeyName: !Not [!Equals [!Ref KeyName, ""]]
  HasUserData: !Not [!Equals [!Ref UserData, ""]]

Resources:
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-ssm-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${ProjectName}-ssm-instance-profile'
      Roles:
        - !Ref SSMRole

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${ProjectName}-launch-template'
      LaunchTemplateData:
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2}}'
        InstanceType: !Ref InstanceType
        SecurityGroupIds:
          - !Ref WebSecGroupId
        IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
        KeyName: !If [HasKeyName, !Ref KeyName, !Ref AWS::NoValue]
        UserData: !If
          - HasUserData
          - !Base64
            Ref: UserData
          - !Ref AWS::NoValue

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier:
        - !Ref PrivSubWeb1Id
        - !Ref PrivSubWeb2Id
      TargetGroupARNs:
        - !Ref TargetGroupArn
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-web'
          PropagateAtLaunch: true

  CpuPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: !Ref CpuTarget

Outputs:
  AutoScalingGroupName:
    Value: !Ref AutoScalingGroup